# Generated by Django 5.2.8 on 2025-11-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main_categoty',
            new_name='Main_category',
        ),
    ]
