# Generated by Django 5.2.8 on 2025-11-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='sub_category',
            new_name='sub_category_name',
        ),
    ]
