# Generated by Django 5.2.8 on 2025-11-25 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_sub_category_sub_category_sub_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='Main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.main_category'),
        ),
    ]
