# Generated by Django 5.2.8 on 2025-11-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_product_sub_category_alter_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phone_no', models.IntegerField(max_length=10)),
            ],
        ),
    ]
