# Generated by Django 5.2.8 on 2025-11-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='phone_no',
            field=models.IntegerField(max_length=15),
        ),
    ]
