# Generated by Django 5.2.8 on 2025-12-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_test_phone_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
