# Generated by Django 5.2.8 on 2025-12-01 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
    ]
