# Generated by Django 5.2.8 on 2025-12-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_color_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='product',
        ),
        migrations.AddField(
            model_name='color',
            name='color_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
