# Generated by Django 5.2.8 on 2025-12-01 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_color_product_alter_color_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.color'),
        ),
    ]
