# Generated by Django 5.2.8 on 2025-12-01 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_product_color_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_price', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='price_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.price'),
        ),
    ]
