# Generated by Django 5.2.8 on 2025-12-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_price_product_price_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='Product_price',
            new_name='product_price',
        ),
    ]
