# Generated by Django 5.2.8 on 2025-12-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_product_price_price_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_key',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
