# Generated by Django 5.2.8 on 2025-12-02 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.price'),
        ),
    ]
