# Generated by Django 5.2.8 on 2025-12-02 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_size_alter_price_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.size'),
        ),
    ]
