# Generated by Django 5.2.8 on 2025-12-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_product_size_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=15)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
