# Generated by Django 5.2.8 on 2025-12-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_user_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_register',
            old_name='username',
            new_name='usern_ame',
        ),
    ]
