# Generated by Django 5.2.8 on 2025-12-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_rename_username_user_register_usern_ame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_register',
            old_name='usern_ame',
            new_name='user_name',
        ),
    ]
