# Generated by Django 5.2.8 on 2025-12-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_rename_usern_ame_user_register_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='email',
            field=models.EmailField(max_length=20),
        ),
    ]
