# Generated by Django 5.2.8 on 2025-12-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='qualtity',
            new_name='quantity',
        ),
    ]
