# Generated by Django 5.2.8 on 2025-12-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_cart_all_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='all_total',
        ),
    ]
