# Generated by Django 5.2.8 on 2025-12-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_checkout_remove_cart_all_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
